version: "3.9"
services:
  app:
    build: .
    user: 'node'
    restart: 'always'
    container_name: ${COMPOSE_PROJECT_NAME-strivee}-app
    working_dir: /usr/app/
    command: 'npm run start:dev'
    ports:
      - ${PORT-80}:${PORT-80}
    volumes:
      - .:/usr/app/
      - .env:/usr/app/.env
      - ./node_modules:/usr/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: ${COMPOSE_PROJECT_NAME-strivee}-postgres
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE_NAME-strivee}
      POSTGRES_USER: ${POSTGRESQL_DATABASE_USER-strivee}
      POSTGRES_PASSWORD: ${POSTGRESQL_DATABASE_PASSWORD-strivee}
    ports:
      - ${POSTGRESQL_DATABASE_PORT-5432}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${COMPOSE_PROJECT_NAME-strivee}-pgadmin
    restart: 'always'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DOCKER_PGADMIN_EMAIL-strivee@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${DOCKER_PGADMIN_PASSWORD-password}
      PGADMIN_LISTEN_PORT: 80
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: 'False'
    ports:
      - ${DOCKER_PGADMIN_PORT-8001}:80
      - ${DOCKER_PGADMIN_PORT_SSL-4431}:443
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    logging:
      driver: none
    depends_on:
      - postgres

volumes:
  pg-data:
  pgadmin-data: